"""One-time verified restoration of the user's complete Orbitarium delivery."""
from pathlib import Path, PurePosixPath
import base64, hashlib, io, json, os, shutil, subprocess, tarfile
root=Path.cwd()
transport=root/'.orbitarium-import'
expected='a809ce8206fbe7ac04f105161ecd263577121044519fc31764329d6b5df03ec0'
parts=sorted(transport.glob('source.part[0-9][0-9]'))
assert len(parts)==9, 'Missing source transport chunks'
payload=b''.join(p.read_bytes() for p in parts)
assert len(payload)==97784 and hashlib.sha256(payload).hexdigest()==expected, 'Source archive integrity failure'
restored={}
with tarfile.open(fileobj=io.BytesIO(payload),mode='r:xz') as archive:
    for member in archive.getmembers():
        p=PurePosixPath(member.name)
        assert member.isfile() and not p.is_absolute() and '..' not in p.parts, 'Unsafe archive member'
        if p.parts[0]=='.github':
            continue  # Workflows are installed separately through the authenticated connector.
        assert p.parts[0] not in ('.git','.orbitarium-import','node_modules'), 'Unsafe destination'
        data=archive.extractfile(member).read()
        target=root.joinpath(*p.parts)
        target.parent.mkdir(parents=True,exist_ok=True)
        target.write_bytes(data)
        restored[str(p)]=hashlib.sha256(data).hexdigest()

def run(*args,env=None):
    subprocess.run(args,check=True,env=env)
run('npm','ci','--ignore-scripts','--no-audit','--no-fund')
run('npm','run','check')
(root/'artifacts').mkdir(exist_ok=True)
tests=subprocess.run(['npm','test'],text=True,stdout=subprocess.PIPE,stderr=subprocess.STDOUT)
print(tests.stdout,flush=True)
(root/'artifacts/github-import-numerical.tap').write_text(tests.stdout)
assert tests.returncode==0, 'Numerical tests failed'
(root/'examples/projects').mkdir(parents=True,exist_ok=True)
subprocess.run(['node','--input-type=module'],input="""
import fs from 'node:fs';
import {createScenario} from '@orbitarium/celestial';
import {Simulation} from '@orbitarium/simulation';
import {stringifyProject} from '@orbitarium/persistence';
for(const key of ['solar','binary','impact','saturn','chaos','galaxy','rogue','empty']){
 const s=createScenario(key), sim=new Simulation(s.store);
 if(key==='impact'||key==='saturn')sim.settings.softening=1e-9;
 const project={...sim.snapshot(),metadata:{title:s.title,scenario:key,speed:s.speed,selected:s.selected},camera:{target:[0,0,0],span:s.span,yaw:-0.3,pitch:0.62,follow:null}};
 fs.writeFileSync(`examples/projects/${key}.orbitarium.json`,stringifyProject(project));
}
""",text=True,check=True)
(root/'release/packages').mkdir(parents=True,exist_ok=True)
run('npm','pack','--workspaces','--pack-destination','release/packages','--ignore-scripts','--json')
env=dict(os.environ)
env.pop('GITHUB_SHA',None)
run('npm','run','build',env=env)
run('node','scripts/verify-pages.mjs',env=env)
verified=[]
for name,digest in json.loads((root/'release/source-sha256.json').read_text()).items():
    if name.startswith('.github/'):
        continue
    assert hashlib.sha256((root/name).read_bytes()).hexdigest()==digest, 'Source mismatch: '+name
    verified.append(name)
packages=json.loads((root/'release/package-manifest.json').read_text())
assert len(packages)==12
for package in packages:
    data=(root/'release/packages'/package['filename']).read_bytes()
    assert hashlib.sha1(data).hexdigest()==package['shasum'], 'Package mismatch: '+package['name']
    assert 'sha512-'+base64.b64encode(hashlib.sha512(data).digest()).decode()==package['integrity']
for name,digest in restored.items():
    assert hashlib.sha256((root/name).read_bytes()).hexdigest()==digest, 'Restored file changed: '+name
for p in (root/'dist').rglob('*'):
    if p.is_file() and p.name not in ('.nojekyll','orbitarium-standalone.html'):
        assert p.read_bytes()==(root/p.relative_to(root/'dist')).read_bytes(), 'Distribution mismatch'
report={'archive_sha256':expected,'archive_bytes':len(payload),'restored_file_count':len(restored),'primary_source_checksums_verified':len(verified),'npm_archives_verified':len(packages),'restored_files':restored,'run_url':os.environ['GITHUB_SERVER_URL']+'/'+os.environ['GITHUB_REPOSITORY']+'/actions/runs/'+os.environ['GITHUB_RUN_ID'],'notes':['Source and generated package archives verified against the delivered hashes.','Normal CI/Pages workflows are installed separately through the GitHub connector.','Screenshot assets are regenerated by browser tests and are not claimed pixel-identical to the earlier local captures.']}
(root/'release/import-verification.json').write_text(json.dumps(report,indent=2)+'\n')
shutil.rmtree(transport)
print('Verified restoration:',len(restored),'source files;',len(verified),'primary checksums; 12 exact npm archives.',flush=True)
